services:
  checkr:
    build: .
    image: checkr
    ports:
      - "3000:3000"
    volumes:
      - ./.config.json:/app/config.json:ro
    environment:
      RUST_BACKTRACE: full
      CONFIG_PATH: /app/config.json
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL